### ISSUE TITLE
about hardware information

### ISSUE THREAD

**Issue by jun0wanan** [Chat-3D/Chat-3D#1]
I would like to train this model of yours or train a model using your data. I'm interested in knowing the approximate duration for training this model and some hardware information. It seems that the paper doesn't appear to have this information.

thanks!

**Comment by Chat-3D** [comment]
Hi, jun0wanan. We are glad to hear of your interest in our work. We have updated the training and hardware information in the README. You can check it out [here](https://github.com/Chat-3D/Chat-3D#-training-and-inference)~
