### ISSUE TITLE
The annotations file of "scanqa_train_stage3.json"

### ISSUE THREAD

**Issue by yangrongkun** [Chat-3D/Chat-3D#10]
Hi, dear authors.
May I ask whether the scanqa_train_stage3.json can be released? When I trained on stage 3, can I use the scanrefer_train_conversation.json for fine tuning?

**Comment by ZzZZCHS** [comment]
Hi Rongkun,

The `scanqa_train_stage3.json` is directly converted from the original ScanQA annotations, but the result of Chat-3D on scanqa is not very good. We have developed a new version, [Chat-3D v2](https://github.com/Chat-3D/Chat-3D-v2), which achieves better results on scanqa, and we will release training and evaluating details on that repo.

You can fine-tune on either `scanrefer_train_conversation.json` or `scanrefer_train_detail.json` (or both) and evaluate on `scanrefer_val_conversation.json` or `scanrefer_val_detail.json` correspondingly. I've updated the `scripts/config.py`.

**Comment by yangrongkun** [comment]
OK, thank you for your fantastic work. I'm looking forward to the full code of Chat-3D v2.
Best wishes！
