### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by rafael1856** [Chat-3D/Chat-3D#13]
Hi, I tried to run it and got this error:

FileNotFoundError: [Errno 2] No such file or directory: 'annotations/scannet_ulip2_feats.pt'

Where can I find the missing file or how can I generate the file ?

Thank you!

**Comment by ZzZZCHS** [comment]
You can download it from [here](https://drive.google.com/drive/folders/1jQQFHeazZQpxKXFZXonrTu2HYSJRlA6T).
