### ISSUE TITLE
The script to generate object-centric annotations from scanrefer annotations

### ISSUE THREAD

**Issue by ZCMax** [Chat-3D/Chat-3D#2]
Thanks for your work, is there any script that can generate object-centric annotations from scanrefer annotations? Although the generated object- centric annotations have been offered.

**Comment by Chat-3D** [comment]
Hi, sorry for the late reply. To generate object-centric annotations, you can refer to Section 4 in our [paper](https://arxiv.org/pdf/2308.08769.pdf). In addition to the prompt for generating detailed descriptions (given in Table 2), we have also released the prompt for generating conversations. You can find them [here](https://github.com/Chat-3D/Chat-3D/tree/main/prompts/dataset_generation) now. 

For interacting with ChatGPT to generate the dataset, we used to use the scripts provided by [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT), but it seems to have become outdated. It's better to use the official [API](https://platform.openai.com/) provided by OpenAI now. We will provide scripts that adapt to the official API when we need to add more training data in the future.
