### ISSUE TITLE
Some bugs in the scripts.

### ISSUE THREAD

**Issue by fanglaosi** [Chat-3D/Chat-3D#3]
Dear authors, It is very grateful to the author for open-sourcing this excellent work.
When I run the scripts following the commands provided in the "readme.md",  the error message occurs as the following:

1. The attribute 'system_path' in config.py
```
File "/home/fangzhongbin/Chat3D/dataset/__init__.py", line 49, in create_dataset
    system_path=config.model.system_path,
AttributeError: 'EasyDict' object has no attribute 'system_path'
```
I checked the project script and found that the attribute "system" has been contained in the config.py. So I overwritten the script of datasets/dataset_val.py&dataset_stage3.py as follows:
```
def __init__(self, ann_file, system="", **kwargs):
    super().__init__()
    self.feat_file, self.attribute_file, self.prompt_file = ann_file[:3]
    self.system = system
```
Though I fixed this bug, I got the other error.

2. Missing the 'annotations/scannet_attributes.json' file.
 File "/home/fangzhongbin/Chat3D/dataset/dataset_stage1.py", line 21, in __init__
    self.attributes = json.load(open(self.attribute_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'annotations/scannet_attributes.json'
Is the 'annotations/scannet_attributes.json' file missing? I can't find the file from anywhere.

Looking forward to your reply!

**Comment by Chat-3D** [comment]
Hi, fanglaosi. We are glad to see your interest in our work.

1. The 'system_path' refers to 'prompts/system.txt'. We forgot to update the corresponding changes in the config.py file. Sorry for the inconvenience.

2. Yes, we missed the scannet_attributes.json when we uploaded the annotations. You can now find it under the [annotations](https://github.com/Chat-3D/Chat-3D/tree/main/annotations) directory.

Hope now you can run the code successfully~
