### ISSUE TITLE
Some questions about scannet_ulip2_feats.pt

### ISSUE THREAD

**Issue by Xiaolong-RRL** [Chat-3D/Chat-3D#4]
Dear author:

Thanks for your interesting work.

when I load scannet_ulip2_feats.pt file, I get a dict which containing the keys such as "scene_0000_xx_yy", could you explain to me in detail the meaning of xx and yy?

In addition, I am very concerned about whether you open source the process of using ulip2 to extract features of a 3D scene, that is, the process of obtaining scannet_ulip2_feats.pt

Thanks!!

**Comment by Chat-3D** [comment]
Hi, Xiaolong. We're delighted to see your interest in our work.

1. The key "scene0000_xx_yy" refers to the concatenation of a scene ID and an object ID, where "scene0000_xx" represents the scene ID, and "yy" represents the object ID.

2. We have provided a more detailed process for extracting the features [here](https://github.com/Chat-3D/Chat-3D/tree/main/preprocess). Hope it will help you.

**Comment by Xiaolong-RRL** [comment]
I see, Thanks!!
