### ISSUE TITLE
some question for scannet attributes

### ISSUE THREAD

**Issue by staymylove** [Chat-3D/Chat-3D#5]
Dear author:
 I want ask that the dim and meaning of 'color' and 'locs' in scannet_attributes.json.
 what is the meaning of the list of color? (such as [0.57, 0.57, 0.55])
 what is the meaning of the list of locs? (every element in locs is 6 dims, such as [-0.2, 1.36, 2.56, 6.71, 7.05, 0.63])

**Comment by Chat-3D** [comment]
The color list [0.57, 0.57, 0.55] refers to the RGB value (normalized to [0, 1]).

The first 3 values in the locs list refer to the location [x, y, z] of the object, while the latter 3 values refer to the size of the object (along the x, y, and z axes, respectively).
