### ISSUE TITLE
Difficulties in debugging code

### ISSUE THREAD

**Issue by Xiaolong-RRL** [Chat-3D/Chat-3D#6]
Dear author:

Thanks for your interesting work.

I have completed the entire process of training and inferencing following the README.md, but now I want to debug the code during the training process to carefully review the details. 

However, I do not know how to debug due to the presence of torchrun, run.sh, and DDP, so I would like to know how you debug in your code, or could you give me some suggestions?

Thanks!!

**Comment by ZzZZCHS** [comment]
Hi, Xiaolong.

I would suggest using the [pdb](https://docs.python.org/3/library/pdb.html) debugger and setting NUM_GPUS to 1 for debugging on a single GPU.

**Comment by Xiaolong-RRL** [comment]
I have tried and it is very convenient! Thanks for your reply!

**Comment by ZzZZCHS** [comment]
You are welcome~
