### ISSUE TITLE
How to get ScanQA eval result?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [Chat-3D/Chat-3D#7]
Dear author:

Could you provide a detailed document for obtaining scanqa eval results? Because I want to verify the validity of the results, especially for scanrefer_val_conversation.json and scanrefer_val_detail.json.

Thanks!!

**Comment by ZzZZCHS** [comment]
Hi, Xiaolong,

We are still in the process of fine-tuning our model on the ScanQA dataset to achieve more satisfactory results. Consequently, we have not yet furnished the evaluation details for the ScanQA dataset.

To evaluate the results for scanrefer_val_conversation.json and scanrefer_val_detail.json, you can utilize caption metrics. I have made updates to the train.py file. You can find the code snippet [here](https://github.com/Chat-3D/Chat-3D/blob/main/tasks/train.py#L223-L242), which is used to calculate caption metrics such as BLEU, METEOR, ROUGE_L, and CIDEr between the reference answers and the generated answers.

For the validation of stage 3, you'll need to prepare a JSON file following this template:
```
[
    {
        "scene_id": <scene_id>,
        "obj_id": <obj_id>,
        "prompt": <question>,
        "ref_captions": [<reference answers>]
    },
    ...
]
```
The questions and reference answers are derived from scanrefer_val_conversation.json and scanrefer_val_detail.json. Currently, we only provide one reference answer for each question, so the length of the ref_captions list is always 1 here.

**Comment by Xiaolong-RRL** [comment]
I see, thanks for your enthusiastic reply!

**Comment by staymylove** [comment]
> I see, thanks for your enthusiastic reply!
May I ask if there are some results of ScanQA_val ? I need the results for my baseline

**Comment by ZzZZCHS** [comment]
Hi, this is the result on ScanQA_val (it will be updated in the arXiv paper later).

<img width="1114" alt="Screenshot 2023-12-13 at 12 47 41" src="https://github.com/Chat-3D/Chat-3D/assets/50910784/25ba4522-03ed-48ca-b3a9-5a1582f824b9">

By the way, we are currently working on a new version of Chat-3D. We have achieved much better performance on ScanQA_val, which will be released at https://github.com/Chat-3D/Chat-3D-v2 soon. Stay tuned.
