### ISSUE TITLE
Question about `scannet_attributes.json`

### ISSUE THREAD

**Issue by Xiaolong-RRL** [Chat-3D/Chat-3D#8]
Dear author:

Thanks for your interesting work.

When I visualized scene0000_00 using locs in scannet_attributes.json, the result is not satisfactory: 

![image](https://github.com/Chat-3D/Chat-3D/assets/74476562/96601b8e-77bd-4209-bad6-d83843b8ed4e)

And I transform [center, size] to corners format [8, 3] by the following code:

```
def get_bbox_corners(bbox):
    centers, size = bbox[:3], bbox[3:6]
    xmin, xmax = centers[0] - size[0] / 2, centers[0] + size[0] / 2
    ymin, ymax = centers[1] - size[1] / 2, centers[1] + size[1] / 2
    zmin, zmax = centers[2] - size[2] / 2, centers[2] + size[2] / 2
    corners = []
    corners.append(np.array([xmax, ymax, zmax]).reshape(1, 3))
    corners.append(np.array([xmax, ymax, zmin]).reshape(1, 3))
    corners.append(np.array([xmin, ymax, zmin]).reshape(1, 3))
    corners.append(np.array([xmin, ymax, zmax]).reshape(1, 3))
    corners.append(np.array([xmax, ymin, zmax]).reshape(1, 3))
    corners.append(np.array([xmax, ymin, zmin]).reshape(1, 3))
    corners.append(np.array([xmin, ymin, zmin]).reshape(1, 3))
    corners.append(np.array([xmin, ymin, zmax]).reshape(1, 3))
    corners = np.concatenate(corners, axis=0) # 8 x 3

    return corners
```

So, I wander how did you generate `scannet_attributes.json`? And is my visualization process correct?

Best!
Xiaolong

**Comment by ZzZZCHS** [comment]
Hi Xiaolong,

We followed [vil3dref](https://github.com/cshizhe/vil3dref/tree/main/preprocess/scannetv2#preprocess-data-for-referit3dnet) to prepare the point cloud information based on the original ScanNet data. The `prepare_scannet_data.py` script would generate instance-level segmented point clouds saved in `{scan_id}_with_global_alignment.pth`. We then used [precompute_instance_bboxes.py](https://github.com/cshizhe/vil3dref/blob/main/preprocess/scannetv2/precompute_instance_bboxes.py) to extract the center and size of each instance.

Your code for `get_bbox_corners` seems to be okay. Could you please provide more information about your visualization process?

**Comment by Xiaolong-RRL** [comment]
Sure! I have sent the detailed processing process to your email. And thanks for your kindly reply~

**Comment by staymylove** [comment]
> Sure! I have sent the detailed processing process to your email. And thanks for your kindly reply~
I also got the same problems, so do you find some ways to solve the problem?
