### ISSUE TITLE
The LLaMa 7B cannot be downloaded now, can the code be adapted to LLaMa 2 ?

### ISSUE THREAD

**Issue by yangrongkun** [Chat-3D/Chat-3D#9]

**Comment by ZzZZCHS** [comment]
Hi, the huggingface link we provided is out of date. Sorry for inconvenience. But I think you can still obtain LLaMA weights from [here](https://huggingface.co/docs/transformers/main/model_doc/llama) by filling out their form. We will also try adapting our model to LLaMA 2.

**Comment by yangrongkun** [comment]
OK,  thanks for your enthusiastic reply, I have downloaded the LLaMA weight. And when I trained on the stage 2, the evaluation of ScanQA seems to meet some errors below:

[Pred] this shelf is between two windows. it is tan and wood.
[Target] a white wooden shelf. on the side of the room.
{'scene_id': 'scene0441_00', 'obj_id': 13, 'qid': 0, 'prompt': '###System: In this task, you will be provided with extensive information regarding objects within a 3D scene. Our conversation will focus primarily on a specific target object, and I will also supply information about all other objects present in the scene.\nTarget object: <TargetHere>.\nAll the objects in the scene: [<SceneHere>]. ###Human: Provide a brief description of the given target object in the 3D scene. ###Assistant: ', 'pred': 'the sink is between the toilet and the wall. the sink is a white rectangle.', 'ref_captions': ['it is a white sink. it is next tho the urinal.', 'above the bathroom sink is a mirror. to the left side of the sink is the bathroom door.', 'to the left of the sink is the paper towel dispenser. above the sink is the bathroom mirror.', 'above the bathroom sink is a mirror. to the left of the sink is a paper towel dispenser.', 'this is the bathroom sink. it is to the left of the urinal.']}
689it [20:15,  1.76s/it]
{'testlen': 30646, 'reflen': 31211, 'guess': [30646, 28580, 26515, 24450], 'correct': [19892, 9896, 4174, 1519]}
ratio: 0.981897407965109
Traceback (most recent call last):
  File "/home/yrk/Desktop/program/Chat3D/Chat-3D/tasks/train.py", line 392, in <module>
    main(cfg)
  File "/home/yrk/Desktop/program/Chat3D/Chat-3D/tasks/train.py", line 338, in main
    global_step = train(
  File "/home/yrk/Desktop/program/Chat3D/Chat-3D/tasks/train.py", line 118, in train
    val_metrics = evaluate(model, model_without_ddp, val_loaders, epoch, global_step, device, config,
  File "/home/yrk/Desktop/program/Chat3D/Chat-3D/tasks/train.py", line 234, in evaluate
    score, scores = scorer.compute_score(tmp_targets, tmp_preds)
  File "/home/yrk/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/pycocoevalcap/meteor/meteor.py", line 43, in compute_score
    scores.append(float(self.meteor_p.stdout.readline().strip()))
ValueError: could not convert string to float: b'27.0 16.0 16.0 10.0 0.0 0.0 9.0 9.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 8.0 9.0 9.0'

**Comment by ZzZZCHS** [comment]
I also encountered this error before, and I solved it according to this [solution](https://github.com/salaniz/pytorch-gve-lrcn/issues/9#issuecomment-467083591). 

Specifically, add `score_line = score_line.replace('\n', '').replace('\r', '')` after line 54 in your meteor.py (/home/yrk/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/pycocoevalcap/meteor/meteor.py).

Check to see if this can solve your problem~

**Comment by yangrongkun** [comment]
Thank you very much for your enthusiastic reply. I will try this method soon.
